global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'dev-app'
    static_configs:
      - targets: ['dev-app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'prod-app'
    static_configs:
      - targets: ['prod-app:8080']
    metrics_path: '/actuator/prometheus'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    metrics_path: '/metrics'
    scrape_interval: 10s
    scrape_timeout: 5s

  - job_name: 'dev-redis'
    static_configs:
      - targets: ['dev-redis-exporter:9121']

  - job_name: 'dev-mysql'
    static_configs:
      - targets: ['dev-mysql-exporter:9104']

  - job_name: 'node'
    static_configs:
      - targets: ['node-exporter:9100']
