spring:
  data:
    redis:
      host: ${REDIS_HOST}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

redisson:
  enabled: true

room:
  qr:
    prefix: "https://zzol.site/join/"

websocket:
  docs:
    enabled: false

springdoc:
  api-docs:
    enabled: false
  swagger-ui:
    enabled: false
