spring:
  data:
    redis:
      host: ${REDIS_HOST}
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    enabled: true
    baseline-on-migrate: true

redisson:
  enabled: true

room:
  qr:
    prefix: "https://dev.zzol.site/join/"

websocket:
  docs:
    server-url: "https://api.dev.zzol.site/ws"

springdoc:
  api-docs:
    enabled: true
  swagger-ui:
    enabled: true
